# Generated by Django 4.2.7 on 2026-04-27 01:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название школы')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('director_name', models.CharField(max_length=100, verbose_name='Директор')),
                ('emergency_mode', models.BooleanField(default=False, verbose_name='Режим ЧС активен')),
                ('emergency_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала ЧС')),
                ('emergency_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания ЧС')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('short_name', models.CharField(max_length=20, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Класс')),
                ('letter', models.CharField(max_length=2, verbose_name='Буква класса')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='administration.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'unique_together': {('school', 'grade', 'letter', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='administration.class', verbose_name='Класс')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ученик в классе',
                'verbose_name_plural': 'Ученики в классах',
                'unique_together': {('student', 'class_group', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='administration.class', verbose_name='Класс')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Классный руководитель',
                'verbose_name_plural': 'Классные руководители',
                'unique_together': {('class_group', 'teacher', 'academic_year')},
            },
        ),
    ]
