# Generated by Django 4.2.7 on 2026-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='classmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
    ]
